// Lista de sugerencias para el autocompletado del campo "Universidad" del registro de
// ingenieros. No es exhaustiva ni restrictiva: el campo sigue siendo texto libre, esto
// solo agiliza la selección para las universidades más comunes en Colombia.
export const UNIVERSIDADES_SUGERIDAS = [
  "Universidad Nacional de Colombia",
  "Universidad de los Andes",
  "Pontificia Universidad Javeriana",
  "Universidad del Rosario",
  "Universidad EAFIT",
  "Universidad de Antioquia",
  "Universidad del Valle",
  "Universidad Industrial de Santander",
  "Universidad del Norte",
  "Universidad Externado de Colombia",
  "Universidad Militar Nueva Granada",
  "Universidad Autónoma de Bucaramanga",
  "Universidad Tecnológica de Bolívar",
  "Universidad de Cartagena",
  "Universidad del Cauca",
  "Universidad de Caldas",
  "Universidad Pedagógica y Tecnológica de Colombia",
  "Universidad Distrital Francisco José de Caldas",
  "Escuela Colombiana de Ingeniería Julio Garavito",
  "Universidad Santo Tomás",
  "Universidad de La Salle",
  "Universidad Católica de Colombia",
  "Universidad Piloto de Colombia",
  "Universidad Antonio Nariño",
  "Universidad Sergio Arboleda",
  "Universidad Icesi",
  "Universidad Pontificia Bolivariana",
  "Universidad de Ibagué",
  "Universidad Cooperativa de Colombia",
  "Universidad Libre",
  "Universidad Manuela Beltrán",
  "Universidad de Pamplona",
  "Universidad Surcolombiana",
  "Universidad del Magdalena",
  "Universidad del Quindío",
  "Universidad Tecnológica de Pereira",
  "Universidad Central",
  "Fundación Universidad de América",
  "Universidad de Medellín",
  "Universidad de San Buenaventura",
  "Universidad EAN",
  "Universidad Nacional Abierta y a Distancia",
  "Universidad del Sinú",
  "Corporación Universitaria Minuto de Dios",
  "Universidad de Córdoba",
  "Universidad de Sucre",
  "Universidad de La Guajira",
  "Universidad Popular del Cesar",
  "Universidad del Tolima",
  "Universidad de Nariño",
  "Universidad Francisco de Paula Santander",
  "Universidad Colegio Mayor de Cundinamarca",
  "Universidad Tecnológica del Chocó Diego Luis Córdoba",
] as const;
